language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.1
  - rbx-2.5.2

before_install:
  - sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra tidy libxml2-utils
  - gem install cmdparse systemu kramdown rake minitest diff-lcs RedCloth haml sass builder coderay erubis rdiscount archive-tar-minitar cssminify
  - gem install rdoc -v '5.1.0'

script: rake test
